name: Verible linting
on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chipsalliance/verible-linter-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        extra_args: "--line-length=500 --banned-declared-name-patterns --numeric-format-string-style --macro-string-concatenation --legacy-genvar-declaration --legacy-generate-region"
        reviewdog_reporter: github-check
