name: Verible linting
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: chipsalliance/verible-linter-action@main
      with:
        # Not specyfing the token causes the linter action to fail entirely.
        github_token: ${{ secrets.GITHUB_TOKEN }}
        extra_args: "--rules_config=.verible-lint-rules"
        fail_on_error: true
        # Hard-specifying the paths and the extensions is done as otherwise
        # it seems like the files in the ./test directory are not picked up.
        paths: |
          ./src
        extensions: |
          .sv
          .v
          .vh
          .svh
